### ISSUE TITLE
When the screen size is reduced the custom message is not displayed.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/admin-color-bar#1]
Open up the Dashboard of a local site, grab the bottom right corner and reduce the size of the screen. 

#![screen shot 2017-07-27 at 7 34 49 am](https://user-images.githubusercontent.com/1041421/28675962-45789dfa-729e-11e7-8e7c-576a06232256.jpg)

DS Version: 3.9
Windows 10
Browser: Edge

**Comment by GreggFranklin** [comment]
Also tested on:
DS Version 3.8.3
Mac
Browsers: Safari, Chrome and Firefox

![screen shot 2017-07-27 at 7 38 11 am](https://user-images.githubusercontent.com/1041421/28676161-cd3fdaa0-729e-11e7-9b7a-f7a570bf31b4.jpg)

**Comment by davejesch** [comment]
This is expected. There's a media query that does a display:none when the screen width is &lt; 1030px.

We could override this, but not sure of the benefit or side effects.

**Comment by GreggFranklin** [comment]
Ok, we'll not worry about this unless a client brings it up and then discuss further.
