### ISSUE TITLE
Admin color bar on front side does not reflect the color change.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/admin-color-bar#3]
Go to Dashboard > Settings > Admin Color Bar
Change color and save
Visit front of website

![image 8](https://user-images.githubusercontent.com/1041421/44479790-78154d80-a5f6-11e8-8dc0-9e00b2176a10.jpg)

![image 9](https://user-images.githubusercontent.com/1041421/44479795-7b103e00-a5f6-11e8-8b4c-a81f66a956d0.jpg)

**Comment by davejesch** [comment]
implemented

**Comment by GreggFranklin** [comment]
Tested, implemented.
